### ISSUE TITLE
Empty geometry flag seems to be unnecessary

### ISSUE THREAD

**Issue by twpayne** [opengeospatial/geopackage#502] opened 2019-10-14 23:20 UTC
The [Geometry Encoding](https://www.geopackage.org/spec121/index.html#gpb_format) includes an "empty geometry flag" specified as:

* Y: empty geometry flag
  * 0: non-empty geometry
  * 1: empty geometry

The specification does not define when this flag should be set or how this it should be interpreted. If the geometry is empty and is not a `POINT` then the WKB encoding of the geometry is sufficient to indicate that the geometry is empty. If the geometry is a `POINT EMPTY` then the specification already specifies how this should be handled (as a point with two quiet NaNs as its X and Y coordinates). Therefore, as far as I can tell, the "empty geometry flag" serves no purpose.

Proposal: deprecate the "empty geometry flag" and indicate that applications should ignore it.

**Comment by jyutzler** [comment] 2019-10-15 17:50
Is there a specific reason you are bringing this up? Are you finding GeoPackages in the wild are treating this bit inconsistently?

My understanding is that this flag was added to the standard so that a client would not be forced to crack open the WKBGeometrys unnecessarily. I am disappointed that there is nothing in the [ATS](https://www.geopackage.org/spec121/index.html#_data_23) about this flag other than tying it to the envelope but I doubt that other members will be inclined to deprecate it.

**Comment by bosborn** [comment] 2019-10-15 22:29
I suspect optimization is a large part of this flags purpose, especially when dealing with [RTree Spatial Indexes](https://www.geopackage.org/spec121/#extension_rtree) and the `ST_IsEmpty` SQL function.  Discussed some in #72.

**Comment by twpayne** [comment] 2019-10-16 00:54
> Is there a specific reason you are bringing this up? Are you finding GeoPackages in the wild are treating this bit inconsistently?

I'm writing code that generates GeoPackages and want to ensure that the generated GeoPackages are correct.

Thanks for the pointers to the reasoning behind the flag. I'll see if I can come up with a PR to clarify this in the spec.

**Comment by jyutzler** [comment] 2019-11-12 16:32
@kryden is going to take a look at this.

**Comment by KRyden** [comment] 2019-12-09 22:46
I am unable to find any notes/documentation on the original motivation for this flag back in 2013 - as noted above, likely to support optimization by not having to crack the more complex geometry WKB in order to determine if a geometry is empty.

The ESRI implementation does set and maintain this flag, and does use it to as an indicator that a geometry is empty, thus avoiding further processing to crack the WKB.  This optimization is specific to Geopackage, as this flag does not exist in non-Geopackage implementations (whether SQLite or other RDBMS).

Removal of this flag would not simplify any shipping software - software in the field is processing this, and would continue to do so.  Removing the flag would require that the field remain in the header for existing software, and that extra logic be added for processing of different versions of Geopackage.

It is recommended that this be addressed by stating that yes, the field is supported, and in use, and that it should remain.  Software should properly set this information as other implementations are dependent on it being correct.

**Comment by twpayne** [comment] 2019-12-13 18:42
Thanks for the investigation :)

**Comment by jyutzler** [comment] 2020-01-21 20:08
We have discovered that this flag is actually used by the st_isEmpty operation that most of the RTree index triggers rely on. Therefore we actually need to make this a SHALL. I believe this is a minor (not major) change that could be included in a 1.3.0 release, but it will require a SWG vote.

As a result, I will update #506 and close #503.

**Comment by jyutzler** [comment] 2020-01-21 20:51
@KRyden When we discussed this, we agreed that the "or" in `either the envelope contents indicator code SHALL be 0 indicating no envelope, or the envelope SHALL have its values set to NaN as defined for an empty point` was incorrect and discussed making it an "and". However, the two possibilities are mutually exclusive. If the E flag is 0 then there are no envelope values (no bytes are allocated for that purpose).

What if we simply eliminate the possibility second possibility entirely? Then the requirement would be that if the geometry is empty you must use the empty flag and vice versa. What do you think?

**Closed** 2020-02-18 18:28 UTC

**Comment by pepijnve** [comment] 2020-02-25 12:43
@jyutzler just adding some historic notes on this one. What I remember is that certain ST_ functions are supposed to return an empty geometry with a specific type. ST_Intersection with for instance needs to return 'empty set of type ST_Point' in some cases for instance. The issue is you can't represent that in WKB. I remember lobbying for NaN as the coordinate values since that was the best way to indicate 'not-defined' with IEEE floating point numbers that I could come up with. Having an explicit 'this is an empty set' indicator made it even more explicit what you were actually getting and avoided having to special case (NaN, NaN) points in the WKB parser.
