### ISSUE TITLE
Request for multiple geometry columns

### ISSUE THREAD

**Issue by Pat28** [opengeospatial/geopackage#77] opened 2014-10-29 14:36 UTC
Referring to https://github.com/opengeospatial/geopackage/issues/19.
Can I request support for multiple geometry columns.

**Comment by jyutzler** [comment] 2015-03-31 17:38
At the 3/31/15 SWG meeting we agreed to close this issue. We felt that the decision to restrict tables to a single geometry column was justified due to the complexity multiple geometries would cause. Client applications would need a way to distinguish primary and secondary geometries and treat them accordingly. The table structure would also need to be more complicated. Since we felt that there were other ways to address this use case, we chose not to support this feature.

We will reconsider this position if you submit a formal [[https://portal.opengeospatial.org/public_ogc/change_request.php][change request]] that clearly describes the justification and use cases for this feature. This would almost certainly be considered an extension and not a change to the existing core.

**Comment by jyutzler** [comment] 2015-03-31 17:43
https://portal.opengeospatial.org/public_ogc/change_request.php

**Comment by Pat28** [comment] 2015-04-01 08:16
I will submit a change request.

The point is that gpkg_geometry_columns (shouldn't this be gpkg_geometry_column without 's'?)
has primary key (table_name, column_name), which indicates you can have multiple geometry columns already.

It is in 2.1.6.1.1. Table Definition, Requirement 30: 
>     A feature table SHALL have only one geometry column, 

that actually restricts the usage of multiple geometry columns.
So removing just Requirement 30 from the spec would be sufficient.

Regards,

Patrick

**Comment by pepijnve** [comment] 2015-04-01 08:39
Simplest way to achieve this will be define a 'gpkg_multi_geometry' extension that relaxes requirement 30. That way the base spec retains the simplicity of single geometry and more advanced usages become possible.

**Comment by Pat28** [comment] 2015-04-01 08:50
By the way, there are a couple of reasons for having multiple geometry columns:

•	Detail geometry versus overview geometry: In many countries for most assets only global position data is known. In addition, for certain area’s or new assets, also the detail geometry is known. It is highly undersired to create the object twice. Also, selecting one, means selecting the other.
•	If you have a cross section or a complex annotation, there is (at least) a point for the text and a line for the leader line (that is another limitation right now, GeoPackage does not have annotation geometry).
•	A directed asset such as a sewage pipe has a line and a flow direction.
•	Certain valves have a position where they are in the pipe network, and another position where the spindle resides.
•	Modeling a park (polygon) with multiple entry/exit points (MultiPoint)

And yes, there are ways of modeling any of these via additional relations (introducing extra tables), but it means additional data integrity rules and possible performance penalty when querying data.

Removing the Requirement 30 is the simplest way in achieving it.

Patrick

**Comment by jyutzler** [comment] 2015-04-07 20:20
Reopening to encourage further discussion.

**Comment by trgn** [comment] 2015-05-13 15:48
I'd be hesitant adding this, mainly because it would not be entirely clear what the meaning of this extra geometry would be. Is this additional geometry a sub-shape of the feature? Does it share the same properties as the main "shape"? Does it need to be visualized by standard viewers? What do we want to do if we want convert this table to a different format? How to index this: is the MBR now the union of all geometry columns?

This is a data-modeling exercise, that is perhaps be better addressed on a higher level (i.e. work with multiple tables, linked with a key. These can be joined on the application level, or with a VIEW).

Also, would a GeometryCollection not be sufficient to achieve a similar capability? The semantics of the constituents of this collections can then be resolved by the user of the collection?

**Comment by Pat28** [comment] 2015-05-13 18:18
What do you mean by 'meaning of this extra geometry'?
I really don't understand why people make/feel so much difference between
alphanumeric fields and indexes versus geometry fields and indexes.
We don't have a main alphanumeric field? or am I missing something?
You don't want to work/use with a GeometryCollection and you don't want to
use multiple table either for quite a few reasons.
I will not give any examples here; just have a set of fields, some being
alpha, some being numeric, some being datetime, some being geometry.
I am not limited to one DATETIME field either.
In Oracle, SQL Server, PostGIS, Smallworld, etc we can model a table with
as many alphanumeric and geometry columns (attributes) as we want; for
whatever reason.
We also just create an index on a field, being alphanumeric or spatial, as
we think is neccessary for performance.
If I choose to explicitly add the centroid of a complex (10-thousends of
points) polygon (for performance reasons) and name it centroid, then I know
what it is (because the name of the field is centroid).
Also when I choose to only display the centroid of a polygon, I do not need
to parse the entire GeometryCollection to figure where the centroid/point
is, I will only request that column from the table (e.g. select centroid
from mytable).
Als, if we have a GeometryCollection with a Polygon and a Point in it, then
what will be the name of the field/column and what does that point mean? Is
it the center or the centroid? or perhaps the entrance of the park? You
just don't know.

In GeoPackage each geometry column would have its own MBR.

To be even more 'restrictive', in my opinion you do not ever want to model
something as being Geometry or GeometryCollection.
Define a geometry column as being a Point, Curve, Polygon, MultiPoint,
etc... be explicit about the contents.
Alphanumeric data is explicit as we have Numeric, CHAR(...), BOOL,
DATETIME, etc..so do the same for geometry, be explicit about the contents.
Whenever someone else (a new employee of your company) looks at the data
model, he/she knows, it's a polygon and then you are sure every record/row
contains a polygon.

Solving the issue with extra tables requires additional overhead/triggers
when adding something to your extra geometry column as there must be a main
record as well.
Same applies when deleting a record from the main table, you must fire a
trigger to delete the extra geometry; if you forget to define the
insert/delete triggers you get data inconsistency; which is what you really
try to avoid.

A simplified example:
I've seen situations where customers created two tables, one named pipe,
the other pipe_hist.
The pipe_hist contains pipes that are still in the ground, but are not
being used anymore (but you must keep track of them for legal purposes)
So to query all pipes of type PVC we now have to join two tables, which
must be in the same shape.
Just having a single pipe table (with two geometry fields) would be much
simpler to query.

Regards,

Patrick

**Comment by trgn** [comment] 2015-05-22 05:18
Not necessarily disagreeing, but just to answer your questions:

My main point was that many GIS file formats only allow for a single geometry per feature. That is a very conventional approach for GIS data formats (GeoJson = 1 geometry per feature, shapefile = 1 shape). It makes it easy for many out-of-the-box applications to do meaningful things with that data.

In the pipe-example: say you load that pipe-table into a general purpose GIS application:

- should the pipes from pipe_hist be shown? (probably not, but we only know that because of this specific use case. There were other use cases where people suggested using these additional columns for sub-shapes. Then you would probably would want it to be shown)
- Can I edit these pipe-histories?
- I now save this out to a shape file. What happens to my pipe-histories?

I understand your concerns with triggers, joining etc..  I would say though for modeling the pipe-history, it does not seem unreasonable at all that people use multiple tables to track historical data. For example, when the main-pipe is edited, it does not require updating the pip_hist value; you can also keep some extra data with each pipe-hist (e.g. a timestamp column with the date it was edited). In my view, it is quite acceptable for relational data models to fall apart into multiple tables, especially when tracking historical data (at least, in my experience). To a certain extent, the technology is designed for that; a join seems perfectly natural in such an environment. I get what you are saying about the triggers though.

Since this seems to be first and foremost a data modeling exercise, which in practice, is often contentious (our discussion being a good example ;)), my inclination would be to take the most conventional approach, 1 feature-1 shape, because those semantics are pretty clear.

**Comment by Pat28** [comment] 2015-05-22 07:56
In my opinion you are confusing GIS databases with GIS export/transport
formats.
GeoJson and Shape are formats for moving GIS data from one place to
another,
can't really say these are GIS format you'd like to perform updates on, or
maintain (insert/update/delete) your data in any of these formats.
From my point of view, GeoPackage is a database, hence it needs to be
treated as a database.

**Comment by pepijnve** [comment] 2015-05-22 09:01
I always saw GeoPackage as both an exchange format and a runtime format. That was the driver behind a lot of the technical arguments I made while we were making the spec. I tried to make it possible to derive as much information as possible from the file itself to allow applications to sensibly use random foreign files. At the same time we kept an eye on the performance impact of our design choices to ensure it would still be feasible to use GeoPackage as a native runtime format for applications.

IIRC the single geometry decision was done to keep things simple for the exchange scenario (correct me if I'm wrong here @jyutzler). If you have multiple geometry columns then you really need some form of application schema mechanism so that different applications can figure out what they're dealing with. At the moment there's no standardised way to encode that kind of information in a GeoPackage. There's gpkg_data_columns, but that can't express these kinds of things.

**Comment by jyutzler** [comment] 2015-05-22 14:55
Due to the large amount of feedback on this topic, I am adding an agenda item for the GeoPackage SWG TC meeting (June 1) to discuss further. For the SWG to consider a new extension, we will look for the following things:
   1. clear use case (I believe we have this now)
   1. sound technical approach that maintains compatibility for systems that just implement the core (not yet...)
   1. commitment from vendors to implement (not yet...)

This is not a priority for me for the reasons @pepijnve describes so I will not be the one building the solution but I will not stand in the way if others do.

**Comment by jyutzler** [comment] 2015-05-22 15:15
If there is someone who is going to the TC who would like to lead this discussion, please let me know. Otherwise I will lead it.

**Comment by jyutzler** [comment] 2015-06-02 23:20
The discussions at the TC yesterday confirmed our previous views. There is minimal interest in creating such an extension (and in fact some members would actively oppose it). We have taken an action to produce guidance on approaches to data modeling that accommodate GeoPackage's one-geometry-column limitation.

**Closed by jyutzler** 2015-06-02 23:20 UTC
